from time import sleep

sleep(3)
print ("Bem vindo ao meu mundo... ")
sleep(3)
print ("As coisas não são tão serenas como você pensa...")
sleep(3)
nome = str(input("Insira o seu nome, estranho: "))
sleep(3)
print("Obrigado,",nome)
sleep(3)
Start = str(input(f"Está pronto para começar esta aventura {nome}? [y/n]: " ))
if Start == "y":
    sleep(3)
    print ("Tudo bem, iremos começar...")
elif Start == "n":
    print("Tudo bem, volte em outro momento..")
    exit()
sleep(3)        
print("Primeiro iremos criar o nosso personagem..")
sleep(3)
print("-"*30)
sexo = ["Masculino","Feminino"]
for n1, s in enumerate (sexo):
    print(n1, s)
print("-"*30)
sexo = input("Selecione o Sexo de seu personagem: ")
print(f"escolha selecionada {sexo}")
sleep(3)
print("-"*30)
estilo_cabelo = ["Social","Curto","Longo","Punk","Raspado","Mullet","Undercut","Militar"]
for n2, e in enumerate (estilo_cabelo):
    print(n2, e)
print("-"*30)
estilo_cabelo = input("Selecione o seu estilo de cabelo: ")
print(f"escolha selecionada {estilo_cabelo}")
sleep(3)
print("-"*30)
cor_cabelo = ["Preto","Branco","Castanho","Verde","Loiro","Azul","Roxo"]
for n3, c in enumerate (cor_cabelo):
    print(n3, c)
print("-"*30)
cor_cabelo = input("Selecione a cor de cabelo de seu personagem: ")
print(f"escolha selecionada {cor_cabelo}")
sleep(5)
print("....")
sleep(5)
print(f"Seu personagem é do Sexo {sexo} tem um estilo de cabelo {estilo_cabelo} da cor {cor_cabelo}")
confirmacao_1 = str (input("Você confirma as informações? [y/n]: "))
if confirmacao_1 == "y":
    sleep(6)
    print ("....")
elif confirmacao_1 == "n":
    print("Reinicie o aplicativo e personalize novamente")
    exit()
sleep(6)
print ("....")
sleep(6)
print ("Carregando..")
sleep(6)
print("-"*50)
print("THE NIGHT OF THE VAMPIRE")
print("-"*50)
sleep(10)
print ("Você acorda em um mundo diferente")
sleep (6)
print ("Não é o mesmo mundo que conhecia antes...")
sleep (6)
print ("O que será que aconteceu com você? ")
sleep (6)
print ("Iremos descobrir... eu espero")
sleep (6)
print ("Sua mente está vazia, não sente muito... mas o brilho da iluminação da lua é ofuscante em sua visão")
sleep (6)
print ("Você olha para as suas mãos.. Estão frias")
sleep (6)
print ("Você vê gotas de sangue manchadas em sua blusa branca... talvez você tenha se machucado?")
sleep (6)
nome = (input ("Consegue lembrar de seu nome?: "))
sleep (6)
print (nome,"...")
sleep (6)
print ("Sim, sim... era eu, era eu aquela noite")
sleep (6)
print ("Em sua mente rápidos flashbacks aparecem, mas desvaneios logo fazem você esquecer o que viu")
sleep (6)
print ("Algo na sua cabeça clama por seu nome...")
sleep (6)
print (f"{nome}.. {nome}..")
sleep (6)
print ("Você apaga.")
sleep (2)
print ("...")
sleep (6)
print("\x1B[3m" + "Hey! mi dá um dolar, mi dá um dolar!" + "\x1B[0m")
sleep(6)
print('"Você acorda com um mendigo vasculhando o seu bolso no meio da praça, rapidamente você percebe a situação e o afasta de você"')
sleep(6)
print("\x1B[3m" + "Mendigo - qui foi cara qui foi! Só tava veno seus borço em busca de din din haha!" + "\x1B[0m")
sleep(6)
print("\x1B[3m" + "Oquié que tu faz aqui no meio da praça dormindo com essa brusa cheia de sangue?" + "\x1B[0m")
